Adding events to your itnerary
SE750-Group14-GirlGang/roadtrip-planner pull request #84
Opened 2021-05-05 00:58 UTC by Jennak21

The user is now able to add events to the days of their road trip
![image](https://user-images.githubusercontent.com/52437731/117086598-1e9ede00-ada1-11eb-8eca-a9a048da6f74.png)

Please note styling and sizing is a bit jank. If the description is one long word, excess will be hidden.
If the screen size is too small a scrollbar appears for the event to show the rest of notes and descriptions.
![image](https://user-images.githubusercontent.com/52437731/117086588-1181ef00-ada1-11eb-8acd-07eb9e04804b.png)

Also I think there is an issue with airbnb react-dates component. If the input date changes and has a different month, the calendar will not automatically switch to that month.

2021-05-06 05:35 UTC, Denijar approved these changes
JENNNAAA this PR pops off I love the way you have implemented this it's so good. Some hella tiny comments but man this is sick. I really don't think the styling jank is worth worrying about at this point.

2021-05-06 05:35 UTC, Denijar commented on frontend/src/components/Itinerary/DailyItinerary/DayCard/AddEventModal/AddEventModal.jsx
> +          <Button onClick={handleClose} color="primary">
actually same for the modal with the datepicker

2021-05-06 05:35 UTC, Denijar commented on frontend/src/components/Itinerary/ItineraryWrapper/ItineraryWrapper.jsx
> +  return <>{loading || !response ? <Spinner /> : <Itinerary itineraryData={response.data} />}</>;
currently the React file structure here breaks convention with the ItineraryWrapper folder being inside the Itinerary folder, even though the Wrapper is the outer component. Can this be refactored?

2021-05-06 05:35 UTC, Denijar commented on frontend/src/components/Itinerary/DailyItinerary/DayCard/AddEventModal/AddEventModal.jsx
> +          <TextField fullWidth autoFocus label="Description" onChange={(event) => setDescription(event.target.value)} />
nit: I think having about 10px margin between the text fields would be nice

2021-05-06 05:38 UTC, Denijar requested changes
Also question - so we are bringing back a "card" style for this page, which I think makes sense for the nature of this page. Maybe for consistency should I put back the shadow around the PackingList? What do you think?

2021-05-06 23:16 UTC, lhuijser commented
> Also question - so we are bringing back a "card" style for this page, which I think makes sense for the nature of this page. Maybe for consistency should I put back the shadow around the PackingList? What do you think?

Yeah it makes sense for the nature of this page- now that this is here I think it makes sense if you want to add the shadow back to the PackingList, but only if you can be bothered, I think it's good either way!

2021-05-06 23:17 UTC, lhuijser approved these changes
This is CLEAN AS HECK Jenna you are a star!! Thank you for this fab implementation!! Love it

2021-05-08 09:59 UTC, Denijar approved these changes
Nice thanks for that file structure change. Very happy to approve that suggestion about the margins was an absolute nit so alggg

2021-05-08 12:00 UTC, courtneyeh approved these changes
Looks amazing!! Amazing job :)

2021-05-08 20:00 UTC, merged